# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class: AppBundle:User 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        unsec:
            pattern: ^/login
            anonymous: ~

        main:
            pattern: ^/
            form_login:
                provider: main
                login_path: login
                check_path: login
                username_parameter: _username
                password_parameter: _password
            logout:
                path: logout
                target: /

    access_control:
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
          - { path: ^/, roles: IS_AUTHENTICATED_FULLY }