# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class: AppBundle:User 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        unsec:
            pattern: “^/(login)$"
            anonymous: ~

        main:
            pattern: ^/*
            anonymous: ~
            access_denied_url: denied_route
            form_login:
                provider: main
                login_path: login
                check_path: login_check
                username_parameter: login[email]
                password_parameter: login[password]
            logout:
                path: logout